### ISSUE TITLE
Export XML on ADLSE Setup Tables (82561, ListPart) does not export anything

### ISSUE THREAD

**Issue by acjdekorte** [Bertverbeek4PS/bc2adls#101]
When trying to use the export xml functionality on ADLSE Setup Tables (82561, ListPart), no data is exported. It seems to be caused by 
UseTemporary property on data items. Is there any reason why these are set to true?

![image](https://github.com/Bertverbeek4PS/bc2adls/assets/36184654/cee82742-2155-4906-a51b-516677fdbd64)

**Comment by acjdekorte** [comment]
Nevermind UseTemporary is required for import :(

**Comment by Bertverbeek4PS** [comment]
@acjdekorte I see it. When I have time I will look into it. 
Strange. It was working.
