### ISSUE TITLE
[Question] How to convert "Last timestamp exported for an updated record" value to datetime ?

### ISSUE THREAD

**Issue by Isarien** [Bertverbeek4PS/bc2adls#113]
Hello,

I want to display the "Last timestamp exported for an updated record" from "ADLSE Table Last Timestamp" table in a dashboard, but it's seems it's not a correct timestamp format.
I read this doc : https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-table-system-fields#timestamp . Can you confirm that it's not real timestamp, but rather a version number

In advance thanks.

**Comment by Bertverbeek4PS** [comment]
Hi @Isarien indeed that is not a real timestamp value.
You can use the last modified date field of a record.

**Comment by Isarien** [comment]
Thank you for your answer
