### ISSUE TITLE
Deployment failed v2.22

### ISSUE THREAD

**Issue by willgart** [Bertverbeek4PS/bc2adls#115]
I can't deploy the v2.22

here the error:
Deployment failed. Errors: App ID : 1688530c-452c-4b06-8947-ab4bf5b26053 Message : { The app (or one of its dependencies) is not available for your release (check the country and version availability in the extension marketplace). }

the v2.21 was deployed without any issue.

not sure which dependency is missing.

**Comment by Bertverbeek4PS** [comment]
What kind of BC version do you have @willgart?
Because version 2.22 is for bc24.

**Comment by willgart** [comment]
thanks for the quick feedback.
I'll close my issue.
