### ISSUE TITLE
missing event when the job queue ends.

### ISSUE THREAD

**Issue by willgart** [Bertverbeek4PS/bc2adls#119]
Hi,

I'm testing the events related to the bc2adsl tool.
the export is finished event is fine, but raised for every table which has been exported and which contains data and not 1 time when the job queue (or the export action) is done.
which is confusing because the event is not telling me which table has been exported and my power automate is triggered multiple times.

so there is a missing event, a real "Export terminated" 
raised 1 time after the export process (not by table) and which should contains the total number of rows exported; or the number of tables which contains exported data.

this will allow us to run a power automate (for example) and start the Fabric job, but only 1 time and only if data has been exported (or not; because no data exported may be a problem I want to identify when we are supposed to have changed data on a regular basis) 

but else, crazy good job!!!

**Comment by willgart** [comment]
if it's the event "Export is finished" , it's the one I'm using
but it is raised for each table and only for the ones with data exported. (so with changes detected)
here the events I'm seeing:
![image](https://github.com/Bertverbeek4PS/bc2adls/assets/20073916/d19c87b7-809b-475a-889d-51fca6950003)

![image](https://github.com/Bertverbeek4PS/bc2adls/assets/20073916/09b8f8a9-4e64-489e-b92d-9c89a3d68968)

I'm using BC23.22

**Comment by Bertverbeek4PS** [comment]
I have also pushed it to the releasebranches 24.23 and 23.22
