### ISSUE TITLE
Error during Export to Fabric / Invalid format on GUID

### ISSUE THREAD

**Issue by LumosPatronum** [Bertverbeek4PS/bc2adls#147]
Hello,
I'm experiencing an error that started today. Previously, I had no issues exporting data regardless of the number of fields I selected or wrote. In fact, I have BC2ADLS installed on my sandbox environment, and exporting the same table to my sandbox Fabric workspace worked flawlessly.
However, in my production environment, I'm encountering an error when trying to add any new table with any number of fields. The error occurs only when I attempt to export the schema with new tables or fields. If I leave the existing 25 tables as is, they export without issues. This is only happening when I try to add additional tables, clear the schema export date, and export schema again to get these new tables into my fabric production workspace.
Please assist me in resolving this error.

**Error message: 
Unable to write content to request stream; content would exceed Content-Length.**
 
Internal session ID: 

Application Insights session ID: 

Client activity id: 

Time stamp on error: 
2024-06-08T17:26:51.6161428Z
User telemetry id: 

AL call stack: 
"ADLSE Http"(CodeUnit 82563).InvokeRestApi - Azure Data Lake Storage Export by The bc2adls team
"ADLSE Http"(CodeUnit 82563).InvokeRestApi line 4 - Azure Data Lake Storage Export by The bc2adls team
"ADLSE Gen 2 Util"(CodeUnit 82568).CreateBlockBlob line 34 - Azure Data Lake Storage Export by The bc2adls team
"ADLSE Gen 2 Util"(CodeUnit 82568).CreateOrUpdateJsonBlob line 5 - Azure Data Lake Storage Export by The bc2adls team
"ADLSE Communication"(CodeUnit 82562).UpdateCdmJsons line 13 - Azure Data Lake Storage Export by The bc2adls team
"ADLSE Execute"(CodeUnit 82561).ExportSchema line 34 - Azure Data Lake Storage Export by The bc2adls team
"ADLSE Execution"(CodeUnit 82569).SchemaExport line 28 - Azure Data Lake Storage Export by The bc2adls team
"ADLSE Setup"(Page 82560)."SchemaExport - OnAction"(Trigger) line 4 - Azure Data Lake Storage Export by The bc2adls team

**Comment by LumosPatronum** [comment]
Hi Bert, thanks for your response! I am exporting to fabric, and you are right, that's exactly what it was. the version i had on my sandbox environment is newer than the one on my production environment. which is why the one on sandbox worked fine. Thanks for confirming. I will mark this as closed!

**Comment by LumosPatronum** [comment]
Hi Bert, It turns out the version I had in my sandbox environment was also about 2 months older, so i downloaded the latest version today and tried installing it on my sandbox environment. I am running into an error when exporting the tables to fabric, well funnily the error message shows up on the export page on ADLSE, but when i go to fabric i can see the new data has arrived in the lakehouse even though ADLSE is giving the following error message:

"Invalid format of GUID string. The correct format of the GUID string is: CDEF7890-ABCD-0123-1234-567890ABCDEF where 0-9, A-F symbolizes hexadecimal digits."ADLSE Communication"(CodeUnit 82562).GetBaseUrl line 15 - Azure Data Lake Storage Export by The bc2adls team\"ADLSE Communication"(CodeUnit 82562).CheckEntity line 26 - Azure Data Lake Storage Export by The bc2adls team\"ADLSE Execute"(CodeUnit 82561).TryExportTableData line 12 - Azure Data Lake Storage Export by The bc2adls team\"ADLSE Execute"(CodeUnit 82561).OnRun(Trigger) line 48 - Azure Data Lake Storage Export by The bc2adls team\"

could you please let me know how to resolve this? 

![Screenshot 2024-06-11 145922](https://github.com/Bertverbeek4PS/bc2adls/assets/172152848/ca17a93f-44ef-499c-9637-5a2a71770c5b)

**Comment by LumosPatronum** [comment]
Hi Bert, 
I just tried this again but replaced both the  workspace and lakehouse with the GUID instead and now it doesn't show the error message on "Last Error" anymore. 
do you know why i wasn't able to run it with the earlier names, they were all lower case. sandbox and sandboxsvroc. 
feel free to close this issue if the solution is to use GUID only. just wanted to keep it open if you thought there was a different issue?

**Comment by Bertverbeek4PS** [comment]
Hi @LumosPatronum thanks for letting me know.
There was an issue with the naming of the workspace.
That was resolved with https://github.com/Bertverbeek4PS/bc2adls/pull/136

That should work. But I will test it after techdays is over.
