### ISSUE TITLE
Schema maximumLength not working correctly for enums not formatted as integer

### ISSUE THREAD

**Issue by bartkraai** [Bertverbeek4PS/bc2adls#148]
maximumLength always contains 4 when an enum column is exported. THis does not correspond with the contents of this field as this is a text export which exports the caption of the enum which can contain more characters. As this maximumLength parameter is not used in the notebook this is no issue there. But as this customer is using a own flow to process the CSV files i came across this issue. It would be great if this can be solved so that this value actually matches the content.

**Comment by Bertverbeek4PS** [comment]
Thanks @acjdekorte for the pull request!
