### ISSUE TITLE
Business Centreal job get deleted

### ISSUE THREAD

**Issue by Jdcfo** [Bertverbeek4PS/bc2adls#155]
Have BC2Adls running on at businesscentral.com. And it runs fine in the jobqueue for 7 days, then the job get deleted. The Business Central support company says it's the extension that is the problem. 
Any ideas why, not a bc person

**Comment by Bertverbeek4PS** [comment]
Hi @Jdcfo,
I have looked inside the code but there is nog deletion of the JobQueue entry.
You can only create a Job queue task and not remove it.

What you can do is setup a change log on the job queue. So then you can track who has deleted the Job queue.

**Comment by WilcoHendriksen** [comment]
An expire datetime is added during creation, [this will remove it](https://github.com/Bertverbeek4PS/bc2adls/pull/158).

**Comment by Jdcfo** [comment]
That's also somewhat what I've guessed, especially since the job was deleted 7 days later.

So now it's set to expire in 1 year to test it.

Thanks
