### ISSUE TITLE
DateTime and Date Data type change error on Export

### ISSUE THREAD

**Issue by Charlottesaliba** [Bertverbeek4PS/bc2adls#156]
Hi Bert,
I am wondering if you have seen an error like this before on the earlier version of bc2adls

We are running on version v. 1.3.14.0 and we receive occasional error on the export from BC. The below example is on table 15 G/L Account.

The data type for the field LastDateModified-26 in the entity GLAccount-15 cannot be changed."ADLSE CDM Util"(CodeUnit 82566).CheckChangeInEntities line 30 - Azure Data Lake Storage Export by The bc2adls team, Microsoft Denmark\"ADLSE Communication"(CodeUnit 82562).CheckEntity line 16 - Azure Data Lake Storage Export by The bc2adls team, Microsoft Denmark\"ADLSE Execute"(CodeUnit 82561).TryExportTableData line 11 - Azure Data Lake Storage Export by The bc2adls team, Microsoft Denmark\"ADLSE Execute"(CodeUnit 82561).OnRun(Trigger) line 48 - Azure Data Lake Storage Export by The bc2adls team, Microsoft Denmark\

**Comment by Bertverbeek4PS** [comment]
Hi @Charlottesaliba I have never seen this issue. And that version is very old.
In this way it will compare the CDM structure that is exported and for the new build one.
Is there some changes made in the CDM structure that is exported? (asume that you are using Azure Data Lake)?
