### ISSUE TITLE
Error during Schema Export: Unable to write content to request stream; content would exceed Content-Length.

### ISSUE THREAD

**Issue by dan-e-williams** [Bertverbeek4PS/bc2adls#157]
Hi,

We are getting an error trying to export schema using BC2ADLS. This is the error with the call stack. BC is on version 24.2.20227.20460

Removing some tables, like Item, a couple of purchasing tables, and a custom table allow it to run, but those tables in particular are getting errors.
  
  If requesting support, please provide the following details to help troubleshooting:
  
  Error message: 
  Unable to write content to request stream; content would exceed Content-Length.
  
  
  Internal session ID: 
  9a4f4624-9c32-482c-be19-d60786e29ed1
  
  Application Insights session ID: 
  fc0fecf0-21f4-492d-8ac7-4fead86824eb
  
  Client activity id: 
  7e0e8407-9307-45c0-be40-63eb91c89bb6
  
  Time stamp on error: 
  2024-07-09T14:45:09.3861286Z
  
  User telemetry id: 
  4bd12488-1d8b-453e-8be8-d0ddc76ea6a3
  
  AL call stack: 
  "ADLSE Http"(CodeUnit 82563).InvokeRestApi - Azure Data Lake Storage Export by The bc2adls team 
  "ADLSE Http"(CodeUnit 82563).InvokeRestApi line 4 - Azure Data Lake Storage Export by The bc2adls team 
  "ADLSE Gen 2 Util"(CodeUnit 82568).CreateBlockBlob line 34 - Azure Data Lake Storage Export by The bc2adls team 
  "ADLSE Gen 2 Util"(CodeUnit 82568).CreateOrUpdateJsonBlob line 5 - Azure Data Lake Storage Export by The bc2adls team 
  "ADLSE Communication"(CodeUnit 82562).UpdateCdmJsons line 13 - Azure Data Lake Storage Export by The bc2adls team 
  "ADLSE Execute"(CodeUnit 82561).ExportSchema line 34 - Azure Data Lake Storage Export by The bc2adls team 
  "ADLSE Execution"(CodeUnit 82569).SchemaExport line 28 - Azure Data Lake Storage Export by The bc2adls team 
  "ADLSE Setup"(Page 82560)."SchemaExport - OnAction"(Trigger) line 4 - Azure Data Lake Storage Export by The bc2adls team 
  

Dan

**Comment by LumosPatronum** [comment]
i too had the same issue a couple weeks ago, are you running the [latest release](https://github.com/Bertverbeek4PS/bc2adls/releases/tag/24.25.0)?
