### ISSUE TITLE
Setting up multi company export - documentation is not up to date

### ISSUE THREAD

**Issue by KoenR3** [Bertverbeek4PS/bc2adls#159]
Hello

We are trying to set up a multi company export using BC2ADLS but the options that are talked about in the documentation are no longer exposed in the UI.  How can an export be set up?

**Comment by Bertverbeek4PS** [comment]
@KoenR3 
Indeed the option is gone. It only prefented you that you cannot change the schema when it is exported.
So what you have do is setting it up in all companies. 
Then run the schema export and on every company you need to create a job queue to schedule the export.

After my holiday I will update the documentation.

**Comment by KoenR3** [comment]
Hey Bert

Thanks for the speedy reply! If we change the company setting it changes in the UI for every company if we switch. Is the job saved with the correct parameters in the background?

**Comment by Bertverbeek4PS** [comment]
Note sure what you mean.
But currently it checks if the schema is exported.
If that is OK then you can export. This job must run in every company. And it will pick up all the changes.

**Comment by Bertverbeek4PS** [comment]
Yes indeed. All the setup will be stored because table is on database level.
But when you do an export the company name is in the export. And if you consolidate the files in your data lake or Fabric you have got just one table for all companies and companyname is on line level. So you know the company.

**Comment by LeivHendrickxTechnoform** [comment]
hi @Bertverbeek4PS , we tried exactly this:
- go to company A, select company A in the dropdown, save
- go to company B, select company B in the dropdown, save

however, only data for company B is exported that way.
so, what are we doing wrong exactly? thx for your help

**Comment by Bertverbeek4PS** [comment]
Hi @LeivHendrickxTechnoform,
In the setup you can choose in the field "Export Company Database Tables" the company where you want to have the tables that are on database level to be exported. Here you have to choose only one company (for exampleCompany A in all your companies).

Then on each company you have to setup a Job Queue with codeunit 82569 "ADLSE Execution" and set the when you want to export it.
In this case it will export from each company in a recurring way.

**Comment by LeivHendrickxTechnoform** [comment]
@Bertverbeek4PS ok, clear. i followed your instructions. will inform next week if things work now as described.

**Comment by LeivHendrickxTechnoform** [comment]
@Bertverbeek4PS : i can confirm all is working well now! thank you for the help!
