### ISSUE TITLE
 Azure Synapse Analytics --> Microsoft Fabric

### ISSUE THREAD

**Issue by DeepAsmani** [Bertverbeek4PS/bc2adls#161]
I am currently use Azure Synapse Analytics now i want to move this process with Microsoft Fabric without disbted current setup

**Comment by Bertverbeek4PS** [comment]
@DeepAsmani You have to fill in your credentials of the MS Fabric lakehouse. 
If that connection is setup you have to reset all the table and then you can export it again with all the tables and fields.
