### ISSUE TITLE
Invalid format of GUID string. The correct format of the GUID string is: CDEF7890-ABCD-0123-1234-567890ABCDEF

### ISSUE THREAD

**Issue by DeepAsmani** [Bertverbeek4PS/bc2adls#166]
Hi @Bertverbeek4PS,
I got error 

**"Invalid format of GUID string. The correct format of the GUID string is: CDEF7890-ABCD-0123-1234-567890ABCDEF where 0-9, A-F symbolizes hexadecimal digits."ADLSE Communication"(CodeUnit 82562).GetBaseUrl line 15 - Azure Data Lake Storage Export by The bc2adls team\"ADLSE Communication"(CodeUnit 82562).CheckEntity line 26 - Azure Data Lake Storage Export by The bc2adls team\"ADLSE Execute"(CodeUnit 82561).TryExportTableData line 12 - Azure Data Lake Storage Export by The bc2adls team\"ADLSE Execute"(CodeUnit 82561).OnRun(Trigger) line 48 - Azure Data Lake Storage Export by The bc2adls team"**

![image](https://github.com/user-attachments/assets/a557106a-6b48-4de6-89b9-ac86504a8c1f)

**Comment by Bertverbeek4PS** [comment]
Hi,
Could you change your workspace and lakehouse in the setup to the guid?
Then it would work. But I will look into the code.

**Comment by DeepAsmani** [comment]
Thanks, Bert, for the speedy reply.

Could you please guide me on where I can find the GUID of the workspace and lakehouse? Also, could you explain how I can send all companies' data to Fabric?

**Comment by DeepAsmani** [comment]
Thanks Bert I will check and let you know

**Comment by DeepAsmani** [comment]
Hi Bert,

It works! Could you also tell me how to send multi-company data? I have 26 companies, and I want to consolidate all the GL entry data into a single dataset in Fabric.

**Comment by Bertverbeek4PS** [comment]
Ok great.
If you want de export in all companies you need to create a Job Queue in each company that exports the data:
https://github.com/Bertverbeek4PS/bc2adls/blob/main/.assets/FAQs.md#how-do-i-run-the-export-to-the-lake-in-a-recurring-schedule
