### ISSUE TITLE
Exporting to multiple target Azure Storage Accounts?

### ISSUE THREAD

**Issue by x3N1GM4x** [Bertverbeek4PS/bc2adls#168]
Is it possible to have bc2adls export to multiple Storage Accounts, or deploy it multiple times to the same BC environment with each deployment pointing at a different target Storage Account?

**Comment by x3N1GM4x** [comment]
Hi @Bertverbeek4PS, thanks so much for the quick response.

Our scenario is that we're in a transitional period after being acquired and while we had bc2adls working fine pre-acquisition, outputting to our chosen Storage Account and then being processed from there into our Data Warehouse, we now need to output the same data in parallel to a Storage Account owned by the acquiring business, so they can begin ingesting the same source data into their Data Warehouse.

If there's no way to do this with bc2adls itself then we'll have to instead put another process in place to copy the data from one location to the other, which is not a big problem, but just requires a few more things to move at our end, so we wanted to check first there was not some easier solution.

**Comment by Bertverbeek4PS** [comment]
Hi @x3N1GM4x no sorry. In bc2adls there is no support of to multiple storage accounts.
I think it is easier to just copy the data in the pipeline that is already there.
So at the final stage in the pipeline you will store it in your own storage account and the one owned by the acquiring business.
