### ISSUE TITLE
Characters Removed from Extracted Data - How does extract handle invalid JSON characters

### ISSUE THREAD

**Issue by tglink72** [Bertverbeek4PS/bc2adls#169]
Hello,

                          We are having an issue with Text fields in Business Central that contain backslashes '\' in them. The \ are removed when viewing the data via Synapse and in the delta and data files themselves. When are the invalid JSON characters escaped out of the data in the BC2ADL process and can this be modified to allow these characters?

Thanks

Tom 

![image](https://github.com/user-attachments/assets/76577f33-e13c-429d-83f5-d42dfc99c1ee)
![image (1)](https://github.com/user-attachments/assets/db4babdf-74cc-4066-a9af-cb0bf1d94b6b)

**Comment by Bertverbeek4PS** [comment]
HJi @tglink72 so currently your scenario is when you export a text field with a '\' in it will be already removed in the .csv file?

**Comment by tglink72** [comment]
Bert,

               Thanks  for the reply. The scenario currently is that when we export a text field with a backslash \ in it. The \ is removed. An example is in the screenshot below.  The regex column has this value in a basic Synapse query. It looks like they are being removed in the initial export to the Delta folder as I do not see the \ in the Regex field in the raw csv in the delta folder.



Regex-3

^Add[A-Z]-d{5}$

But if we view the data in BC below you will see it contains \ that are not included in the query.

***@***.***

**Comment by Bertverbeek4PS** [comment]
Thanks @tglink72 I then look if I can repo it. Hopefully I have got time for it this week.

**Comment by Bertverbeek4PS** [comment]
@tglink72 I did a test with the export to MS Fabric Lakehouse.
Customer comments:
![image](https://github.com/user-attachments/assets/82d31fe2-6a76-42f1-a625-b85e3fcc10bc)
Then export to csv delta file:
![image](https://github.com/user-attachments/assets/ed6dc669-0367-4935-8522-29e9d072d651)
When the notebook is runned:
![image](https://github.com/user-attachments/assets/861aafd5-35a0-4270-8b2f-cff615ae805d)

So with Fabric it goes well. 
I will also look into export of Azure Data Lake

**Comment by Bertverbeek4PS** [comment]
@tglink72 
I have also tested it with the synapse pipelines and Azure File Storage.
But cannot reproduce it.

WHen exporting the delta's:
![image](https://github.com/user-attachments/assets/951b7fcb-3210-4004-92ae-e6ed3a6dd0f6)

WHen the synapse pipeline runs and in PowerBI:
![image](https://github.com/user-attachments/assets/51a25036-b913-43b9-93d7-73cc58d10ed2)

I'm using parquet files as destination.

**Comment by tglink72** [comment]
Bert,

               Thanks for the replies. I am also using synapse pipeline and Azure File storage and unfortunately, I can create it each time. The backslash is removed in the extension extract to the deltas folder. If you would like we could do a screenshare.

Thanks

Tom Link

**Comment by Bertverbeek4PS** [comment]
Ok strange @tglink72 . Which version do you have?
Indeed is it OK to have a meeting? On friday I got the whole afternoon available.

**Comment by tglink72** [comment]
Bert,

               Hello. Would you be able to meet anytime this week. I can meet early morning central time US.

Thanks

Tom Link

**Comment by Bertverbeek4PS** [comment]
@tglink72 this week I cannot make it.
But next week monday or Teusday 13:00 - 17:00 GMT+2

**Comment by Bertverbeek4PS** [comment]
Closed because no respond. Please reopen this issue when it is still there.
