### ISSUE TITLE
OpenSSF

### ISSUE THREAD

**Issue by leonsparrowJM** [Bertverbeek4PS/bc2adls#172]
Hello, 
if it possible for you to submit a score to openSFF please?

https://github.com/ossf/scorecard?tab=readme-ov-file

So we can build a picture of the security around the repo?

**Comment by Bertverbeek4PS** [comment]
Thanks @leonsparrowJM I have added it.
Need to check all the warning. Some are AL-Go for Github related. So that I cannot fix.
