### ISSUE TITLE
Lakehouse folder structure

### ISSUE THREAD

**Issue by Prenamix** [Bertverbeek4PS/bc2adls#179]
Hi,

I wonder if could be an idea to allow the user to define the folders in which the files from BC are placed in the receiving Fabric lakehouse?

As it is now the files will be placed in the root Files folder and in Files/delta. It would be nice to be able to tell the code to place files in e.g. Files/BusinessCentral/

This would allow for a cleaner lakehouse that can easily be used with other source systems. Or am I missing something?

Thanks

**Comment by Bertverbeek4PS** [comment]
@Prenamix Currently that is indeed not possible. Everything goes to the root.
Moslty the idea is to have one lakehouse per source for the raw data. 
Later on you can group and clans your data in a warehouse or another lakehouse.

**Comment by bjarkimg** [comment]
I agree on this, separate lakehouse per ENV, then combine in a warehouse/lakehouse,
and get used to this structure since BC will not be the only source data in the warehouse going forward :)

**Comment by Bertverbeek4PS** [comment]
Closed beacuse no respond. Please reopen this isseu when it is still there.
