### ISSUE TITLE
Periodic Cleanup of the ADLSE Run Table Not Possible

### ISSUE THREAD

**Issue by rubenbudding4PS** [Bertverbeek4PS/bc2adls#191]
Periodic cleanup of the ADLSE Run table (table number: 82566) is not possible. This is particularly challenging when Azure Data Lake is utilized across multiple companies, as the table size tends to grow rapidly. In just three months, the ADLSE Run table is accumulate over 100,000 log run records.

**Comment by Bertverbeek4PS** [comment]
Fixed with PR: https://github.com/Bertverbeek4PS/bc2adls/pull/192
