### ISSUE TITLE
Bug Report: Fabric Lakehouse Table Creation Results in "Unidentified" State

### ISSUE THREAD

**Issue by DataInsightPro** [Bertverbeek4PS/bc2adls#206]
# **Issue Summary**
When using `df.write.format("delta").save("Tables/" + table_name)` to create or update tables in a Microsoft Fabric Lakehouse **with schema support enabled**, the resulting tables are not properly recognized in the Lakehouse catalog. Instead, they appear in an "unidentified" state with the error **"unable to identify these objects as tables"**.

# **Environment**
- **Platform**: Microsoft Fabric
- **Feature**: Lakehouse with Schema Support (Preview) enabled
- **Affected Method**: Delta table write using `.save()` with a manual path

# **Steps to Reproduce**
1. Target a Microsoft Fabric Lakehouse with **Lakehouse Schema Support** enabled.
2. Use the bc2alds notebook code to write a Delta table:
   ```python
   df_new.write.mode("overwrite").format("delta").save("Tables/" + table_name)
   ```
3. After execution, inspect the table list in the Lakehouse UI.

# **Observed Behavior**
- The table appears in the Lakehouse, but its state is **"unidentified"**.
- The error message indicates **"unable to identify these objects as tables"**.
- Querying the table fails since it is not properly registered in the Lakehouse catalog.

# **Root Cause**
The issue occurs because **schema support** requires tables to be registered with an explicit schema context in the Lakehouse. Writing directly to a path using `.save()` bypasses the schema registration process, causing the Lakehouse to misinterpret the table metadata.

# **Workarounds**
Use `saveAsTable()` to register the table in the catalog **without explicitly specifying the schema**:
   ```python
   df_new.write.mode("overwrite").format("delta").saveAsTable(f"{table_name}")
   ```

# **Recommended Fix**
Update the notebook to utilize the `saveAsTable()` method instead of the `save()` method.

   - If schema support is enabled, the table defaults to the `dbo` schema.
   - If schema support is disabled, the table should still work without errors.
  
Optionally, set the schema explicitly using a variable:
   ```python
   schema_name = "my_schema"
   df_new.write.mode("overwrite").format("delta").saveAsTable(f"{schema_name}.{table_name}")
   ```

**Comment by Bertverbeek4PS** [comment]
Thanks allot for reporting this @DataInsightPro ! Added an option to add a schema name.
If that is empty then it will be saved without a schema.
