### ISSUE TITLE
Last export state stops on "In process"

### ISSUE THREAD

**Issue by Arthurvdv** [Bertverbeek4PS/bc2adls#21]
Sometimes the Last exported state seems not to be updated to Succes.

![image](https://github.com/Bertverbeek4PS/bc2adls/assets/44637996/2a37dc02-9986-49c0-bde7-71f8f7bc8c7d)

It's difficult to describe the repro steps to create this situation.
The good news is that in a next run it seems that this issue will resolve itself, where it's not blocking issue.

**Comment by Bertverbeek4PS** [comment]
Never had that experience. 
Even a refresh doesn;t help?

**Comment by Arthurvdv** [comment]
The problem seems to be that the Ended field on the ADLSE Run (82566) table isn't populated. It seems we're not reaching the ```RegisterEnded``` method in the "ADLSE Run" table.

I was hoping to find a result on the ADLSE-035 Telemetry, but no luck. 

![image](https://github.com/Bertverbeek4PS/bc2adls/assets/44637996/3a063b91-2329-4928-a43e-939e4720f780)

**Comment by Bertverbeek4PS** [comment]
With your newest pull request. Is that resolving the issue also?

**Comment by Arthurvdv** [comment]
That was not the intent the pull-request and unfortunately the issue still persists.

![image](https://github.com/Bertverbeek4PS/bc2adls/assets/44637996/278243e0-58d1-4f16-820b-18236142ff60)

I'll try to investigate more in depth if I can find why this is failing sometimes.

**Comment by Arthurvdv** [comment]
![image](https://github.com/Bertverbeek4PS/bc2adls/assets/44637996/d2395f26-811b-49bb-a5c9-68e5066cd6b9)

Based on the telemetry it seems the SetStateFinished method failed somehow. I'm going to add some more telemetry and monitor the next couple of days if I can pinpoint the exact location where it's failing.

codeunit 82561 "ADLSE Execute"
```AL
trigger OnRun()
...

    // update Jsons
    ADLSECommunication.UpdateCdmJsons(EntityJsonNeedsUpdate, ManifestJsonsNeedsUpdate);
    if EmitTelemetry then
        ADLSEExecution.Log('ADLSE-007', 'Jsons have been updated', Verbosity::Normal, CustomDimensions);

    // Finalize
    SetStateFinished(Rec, TableCaption);
    if EmitTelemetry then
        if ExportSuccess then
            ADLSEExecution.Log('ADLSE-005', 'Export completed without error', Verbosity::Normal, CustomDimensions)
        else
            ADLSEExecution.Log('ADLSE-040', 'Export completed with errors', Verbosity::Warning, CustomDimensions);
end;
```

**Comment by Arthurvdv** [comment]
Issue has been resolved: https://github.com/Bertverbeek4PS/bc2adls/commit/7653e073438e68805951e530b507f0355b0d5c22
