### ISSUE TITLE
Question for External Business Event with upcoming Microsoft Fabric integration

### ISSUE THREAD

**Issue by Arthurvdv** [Bertverbeek4PS/bc2adls#22]
```AL
[ExternalBusinessEvent('ExportOfEntityEnded', 'Entity export ended', 'The export of the entity was registered as ended.', EventCategory::ADLSE)]
local procedure TableExportRunEnded(RunId: Integer; State: Enum "ADLSE Run State"; Container: Text[250]; EntityName: Text[250])
begin
end;
```

I would like to add an second External Business Event as ExportEnded, so we also could integrate when all the exports of the entities are finished.

![image](https://github.com/Bertverbeek4PS/bc2adls/assets/44637996/ebab0a63-93b1-4dce-a8c7-1bcc2d3430e5)

With the upcoming Microsoft Fabric integration I'm struggling a bit what the best approach is on this.

1. Do we create a separate event for each type of Storage Type (ADLS/Fabric) or one independent of the Storage type?
2. In case for one generic type, I'm not sure how to handle the different parameters between the different Storage types. Include all four (Container, Account name, Workspace and Lakehouse) or make a generic name for Account name and Workspace and also a generic name for Container and Lakehouse?
3. Not sure why the Account name parameter is in the Isolated Storage. I would like to expose this in the event. For performance reasons I guess it would be better to migrate this field out of the Isolated Storage and to a field on the setup table. Are there any concerns on having this field on the table and exposed in the event?

**Comment by Bertverbeek4PS** [comment]
@Arthurvdv I would suggest one generic event for both storage type with generic names like:
Environment and resource.
Maybe also include the storage type in the business event.
For the Account Name it is fine do put it outside the isolated storage. Maybe it is good to create a upgrade path for it.
