### ISSUE TITLE
Error: Collection was modified; enumeration operation may not execute

### ISSUE THREAD

**Issue by Sr1983** [Bertverbeek4PS/bc2adls#25]
Hi,
we have encountered the error "Collection was modified; enumeration operation may not execute" during the last 2 day (never happened till now).

The error is related to the Synapse Pipeline "Consolidation_OneEntity", activity "Switch - Copy Staging to data - Copy Parquet".

In previous github repository was reported the same error yesterday:
https://github.com/microsoft/bc2adls/issues/138

Have you got any idea to solve the issue?  It happen randomly on different entity (apparently without a logic).

**Comment by Bertverbeek4PS** [comment]
Is there maybe data that is deleted?

**Comment by Sr1983** [comment]
Hi thank you for yuor answer; we don't have any evidence about data deleted. It's really strange because we are using the pipeline from 3 month and this issue never happened.
In the other post, the user says the he solved, removing the entity and adding it again.
Is it possible?

**Comment by Bertverbeek4PS** [comment]
In pull request:
https://github.com/Bertverbeek4PS/bc2adls/pull/14
There is a change of paritioning in the dataflow. 
If you import that change and run it again.
