### ISSUE TITLE
Microsoft Fabric - Howto handle FlowFields

### ISSUE THREAD

**Issue by Arthurvdv** [Bertverbeek4PS/bc2adls#27]
Could it be helpful to include in the documentation on this project on what the best approach is on handling Flow Fields from Business Central to OneLake of Microsoft Fabric combined with Direct Lake?

![image](https://i0.wp.com/radacad.com/wp-content/uploads/2023/06/directlake-diagram-1.png)

For example when export the item entity from Business Central and want to include the Inventory as a column.

```AL
  field(68; Inventory; Decimal)
  {
      CalcFormula = Sum("Item Ledger Entry".Quantity WHERE("Item No." = FIELD("No."));
      ...
      FieldClass = FlowField;
  }
```

The first step will be to also expose the "Item Ledger Entry" entity with the Quantity column. Form there, is this a Measure to include for every report over-and-over again? Or use a DataFlow to create a second Lakehouse to do the calculation/transformation? Or is there another (better) way of archiving this?

**Comment by Arthurvdv** [comment]
Thank you for elaborating on this, that's very helpful! My first thought was on placing the Lakehouse in the center, but it makes sense (in my use case) to have a Warehouse in the center and move the data into there.

Are there plans to include a template in the project like there's for Azure Synapse? This could help lower the learning curve to get started with Microsoft Fabric. Or is this more suitable for a (online) course to be held in the future?

**Comment by Bertverbeek4PS** [comment]
If you want to use flowfields then a warehouse is better.
Well it is difficult to create a template. Because mostly a warehouse is customization.
But an example is possible indeed. Then a user can get that example and move further. That could be an idea.
