### ISSUE TITLE
Pull requests from original project

### ISSUE THREAD

**Issue by jespertheil** [Bertverbeek4PS/bc2adls#3]
Hi Bert, 

Good to see action has been taken to maintain this project. We are in process of deploying it as part of a BC project. 

There is a pull request on the original project with a fix that we use at the moment - stops export from BC hanging as "In process" forever when running On-premise. 

It's the microsoft#130 fix from this pull request : https://github.com/cegeka-dsa/bc2adls/pull/13

Have you considered moving that over to this project? 

Best regards
Jesper Theil

**Comment by RonKoppelaar** [comment]
Full link the the Issue in MS repo: https://github.com/microsoft/bc2adls/issues/130

**Comment by Bertverbeek4PS** [comment]
@jespertheil @RonKoppelaar there must be a pull from master to resolve the conflict.

**Comment by Bertverbeek4PS** [comment]
Closed with https://github.com/Bertverbeek4PS/bc2adls/pull/5
