### ISSUE TITLE
Job Queue entry in BC deleted

### ISSUE THREAD

**Issue by jtaisbak** [Bertverbeek4PS/bc2adls#54]
Problem: One of my clients got the problem that the job queue entry i deleted

Scenario: 
1) BC2ADLS extension is configured in BC
2) Job Queue entry configured in BC (delta update every second hour every day between 6.00 and 20.00
3) after a period of time (several days) the job queue entry is deleted with the user credentials of the user who configured the job queue entry and the extension

Question: 
1) Does the BC2ADLS extension delete the job queue entry in some scenarios ? 
2) How can we avoid this operation to occur ?

**Comment by Bertverbeek4PS** [comment]
Hi @jtaisbak, the bc2adls extension doesn't delete the JobQueue.
Not sure if there is an end date set in the JobQueue?

**Comment by jtaisbak** [comment]
> Hi @jtaisbak, the bc2adls extension doesn't delete the JobQueue. Not sure if there is an end date set in the JobQueue?

Correct, it was the "hidden" end date.
