### ISSUE TITLE
Consolidation_OneEntity Pipeline JSON error

### ISSUE THREAD

**Issue by erik-stefanov** [Bertverbeek4PS/bc2adls#57]
Hello,

When trying to implement the Consolidation_OneEntity pipeline we get the following error when trying to save it:
Could not load resource 'Consolidation_OneEntity'. Please ensure no mistakes in the JSON and that referenced resources exist.

Could you please assist?

**Comment by erik-stefanov** [comment]
Hello, 

Yes, I am aware of the sequence. Here are all the previous steps created:
![image](https://github.com/Bertverbeek4PS/bc2adls/assets/150233733/73dca5e7-0eb5-487c-b2dc-c0c9d7e80313)
![image](https://github.com/Bertverbeek4PS/bc2adls/assets/150233733/9b3cb0fd-7c8b-4447-8b8e-69833771e14a)

However the Consolidation_OneEntity pipeline cannot be created because of the above mentioned issue.

**Comment by Bertverbeek4PS** [comment]
Do you have published the previous datasets? 
(it is a while ago that I have installed the synapse pipelines). 
Otherwise maybe setup a meeting?

**Comment by erik-stefanov** [comment]
Yes, everything has been published. I think a quick meeting would be helpful. Let me know a suitable time frame for you.

**Comment by Bertverbeek4PS** [comment]
Hi @erik-stefanov  i can do tomorrow afternoon 13:00-17:00 (UTC+1)

**Comment by erik-stefanov** [comment]
Hi, lets meet at 13:00
https://teams.microsoft.com/l/meetup-join/19%3ameeting_YjdiOTk0N2QtMDhjZS00NzM5LWFjN2YtYjIzNGI5Zjk0Yjlj%40thread.v2/0?context=%7b%22Tid%22%3a%2242151053-0193-47aa-9e81-effd81f772cc%22%2c%22Oid%22%3a%2296eaf611-fe6b-4b9d-bfab-dc94e248d91f%22%7d

**Comment by Bertverbeek4PS** [comment]
Creation of notebook wasn;t in the order in the setup manual.
Fixed that with pull request:
https://github.com/Bertverbeek4PS/bc2adls/pull/58
