### ISSUE TITLE
Upgrade to 23.1 fails

### ISSUE THREAD

**Issue by epernst** [Bertverbeek4PS/bc2adls#61]
Just tried to upgrade our solution to BC v23.1 (w1) with Bc2adls and it fails with:
Start-NAVAppDataUpgrade : Could not upgrade the extension 'Azure Data Lake Storage Export' by 'The bc2adls team' from v
ersion '1.3.12.144898' to '1.3.12.148352' for tenant 'default' and company '' due to the following error: 'The followin
g table fields cannot be exported. Please disable them. [G/L Account]: , [Sales Header]: Received-from Country/Region C
ode, [Company Information]: IC Partner Code, [Sales Cr.Memo Header]: Received-from Country/Region Code, [Sales Header A
rchive]: Received-from Country/Region Code, ' and AL stack trace: 
"ADLSE Upgrade"(CodeUnit 82572).OnCheckPreconditionsPerDatabase line 11 - Azure Data Lake Storage Export by The bc2adls
 team
"Upgrade Triggers"(CodeUnit 2000000008).OnCheckPreconditionsPerDatabase(Event) line 2

Any advise?

**Comment by Bertverbeek4PS** [comment]
Those fields are put on ObsoleteState = Removed.
On every upgrade of bc2adls and the environment it will check if fields are removed.
So disable those fields for exporting and you can run the upgrade again.

In this way you prevent rong data or errors.

**Comment by epernst** [comment]
Ok, that's clear, but can you tell me which field to disable for G/L Accounts? The list of fields here is not shown.

**Comment by Bertverbeek4PS** [comment]
Strange that isn;t there. But I can see in the source that field ID is put on obsolete removed.

**Comment by epernst** [comment]
We found out that the field in G/L Account, that is not displayed is from a Microsoft app, that we no longer have installed. So, the warning is correct, even if it is not listing the correct field name.

**Comment by Bertverbeek4PS** [comment]
Ah good to know. Thanks for reporting back!
