### ISSUE TITLE
Fabric - CopyBusinessCentral.ipynb - multi-company export

### ISSUE THREAD

**Issue by lhammerbh** [Bertverbeek4PS/bc2adls#62]
Dear Bert and Co.

We are testing multi-company export in Fabric mode.

The export of data using the bc2adlse component is working perfectly fine.

When we are running the CopyBusinessCentral python script, we seem to be missing out some of the values.
The reason seems to be that in a multi-company export, the system id in the same table for different companies may have the same systemid value.

A possible solution could be add $Company to the df_new.dropDuplicates, so the code could be:

 # remove duplicates by filtering on systemID, $Company and systemModifiedAt fields
 df_new = df_new.orderBy('systemId-2000000000',['$Company'],desc('SystemModifiedAt-2000000003'))
df_new = df_new.dropDuplicates(['systemId-2000000000'],['$Company'])

Yours
Lars Hammer

**Comment by Bertverbeek4PS** [comment]
Hi @lhammerbh you are totally right. 
I though that I have changed that. And Company must be there. I will fix this today!

**Comment by Bertverbeek4PS** [comment]
Same issue as https://github.com/Bertverbeek4PS/bc2adls/issues/56

**Comment by Bertverbeek4PS** [comment]
@lhammerbh in the newest version in the repro the bug is fixed with the modified fields and the deleted records.
