### ISSUE TITLE
Fabric Notebook Trigger. Request for info

### ISSUE THREAD

**Issue by lhammerbh** [Bertverbeek4PS/bc2adls#64]
Hi Bert

We are now successfully running BC2ADLS in a Fabric setup. Data are coming through correctly, and the fabric notebook is working beautifully in the new version.

I have seen that in the data lake version, you have suggested a Power Automate app that can trigger the data factory pipeline corresponding to the notebook.

Have you been looking into the how we can trigger the notebook in the Fabric solution, when the BC2ADLSE component has completed the delta export? Or do you have any thoughts on this?

I have been looking into, whether it is possible to use the Fabric Rest API's, that could be called from a Power Automate app:
https://learn.microsoft.com/en-us/rest/api/fabric/articles/?source=recommendations
Especially the notebooks api:
https://learn.microsoft.com/en-us/fabric/data-engineering/notebook-public-api

But I am having issues getting it to work.

Sorry to use the issues list for this, but I didn't know, where else to put it.

Yours
Lars Hammer

**Comment by Bertverbeek4PS** [comment]
A couple weeks ago the API wasn't there. 
Properly this wil indeed work maybe:
https://learn.microsoft.com/en-us/fabric/data-engineering/notebook-public-api#run-a-notebook-on-demand

But I have never tried it. Need to try it maybe. That will be a good idea. Then we can use also a Power Automate function for it.

**Comment by Bertverbeek4PS** [comment]
@lhammerbh you can indeed run the Notebook through the API!
So in that case you can trigger the Business Event from BC in Power Automate or Logic App then start the notebook.

You can do that with an Post to:
https://api.fabric.microsoft.com/v1/workspaces/<workspace GUID>/items/<Notebook GUID>/jobs/instances?jobType=RunNotebook

And in the body the following JSON:
{
    "executionData": {
       
    }
}

Scope of the request must be:
https://api.fabric.microsoft.com/Item.ReadWrite.All

And in the app registration the following permissions:
![image](https://github.com/Bertverbeek4PS/bc2adls/assets/71499421/d6fab277-a7d9-46ac-b8f5-4a141da7d565)

**Comment by lhammerbh** [comment]
Did you get this to work, Bert?

I'm having a hard time to get it to work in Postman. It keeps telling me "BadRequest". And I tried to follow your recipe.

Sorry to ask you about this, but maybe you can help me further:

My call is a POST to https://api.fabric.microsoft.com/v1/workspaces/{{WORKSPACE_ID}}/items/{{ARTIFACT_ID}}/jobs/instances?jobType=RunNotebook
Workspace_ID is id of workspace and ARTIFACT_ID is id of notebook

Body is:
{
    "executionData": {
        "parameters": {
            "parameterName": {
                "value": "new value",
                "type": "string"
            }
        },
        "configuration": {
            "conf": {
                "spark.conf1": "value"
            },
            "defaultLakehouse": {
                "name": "grm_bc2adls_lakehouse"
                
            },
            "useStarterPool": true
        }
    }
}

Can you share how you did it successfully?

**Comment by Bertverbeek4PS** [comment]
I have indeed got it working. 
In the body you can only have this:
{
    "executionData": {
       
    }
}

Nothing more.

And for getting the credentials:
![image](https://github.com/Bertverbeek4PS/bc2adls/assets/71499421/ee6aa1b6-bd15-4f25-a459-98eabf842b02)

![image](https://github.com/Bertverbeek4PS/bc2adls/assets/71499421/2a94618e-bcdc-4218-a936-9106194294bd)

**Comment by lhammerbh** [comment]
Thanks for your help, Bert.
I am following your recipe.
Unfortunately, I am still getting a BadRequest.
The token is coming back as it should.
The request is a POST with https://api.fabric.microsoft.com/...../[WORKSPACE_ID]/items/[NOTEBOOK_ID]/jobs/instances.....
The body is only containing empty "executionData", like you specified.

I am wondering, if I need to enable something in the Fabric configuration, or if I am missing something else.

![image](https://github.com/Bertverbeek4PS/bc2adls/assets/69352441/49278052-ce78-46ec-b9fb-e3518a57ffb0)
![image](https://github.com/Bertverbeek4PS/bc2adls/assets/69352441/48315eb5-da3e-40cf-af67-bd8d107a9a00)
![image](https://github.com/Bertverbeek4PS/bc2adls/assets/69352441/12519e4a-48c2-46a1-ba1d-9f7be71e44b1)

**Comment by Bertverbeek4PS** [comment]
You don't have to setup anything in Fabric.
Only in the API set the permissions:
![image](https://github.com/Bertverbeek4PS/bc2adls/assets/71499421/fc72cae4-6daf-47f3-81c5-a324c0fdcb2c)

ANd is your GUID workspace correct?

**Comment by Bertverbeek4PS** [comment]
And can you get all items with a GET request to:
https://api.fabric.microsoft.com/v1/admin/items

**Comment by Bertverbeek4PS** [comment]
My Auth URL is:
https://login.microsoftonline.com/{{TenantId}}/oauth2/v2.0/authorize

Access Token URL is:
https://login.microsoftonline.com/{{TenantId}}/oauth2/v2.0/token

Otherwise we can plan a meeting.

**Comment by lhammerbh** [comment]
If you do have the time, Bert, that is highly appreciated.
I'm available today between 13-15 CET.
Or tomorrow between 11-12 CET
Or friday between 9-11.30 CET

**Comment by Bertverbeek4PS** [comment]
Lets do friday. I can also between 9-11.30 CET.
Could you send me an invite to bverbeek@4ps.nl?

**Comment by Bertverbeek4PS** [comment]
Created a blog post also about this:
https://www.bertverbeek.nl/blog/2024/01/16/trigger-a-fabric-notebook-through-the-api/
