### ISSUE TITLE
Disabling Obsolete Fields

### ISSUE THREAD

**Issue by greglong1** [Bertverbeek4PS/bc2adls#66]
I am doing some investigation into BC 23.1 and have also come across the issue that field ICParterCode-41 in entity CompanyInformation-79 is now obsolete.  In my 22.5 sandbox I'm having an issue disabling this field and want to know exactly what the procedure is.  We are using the implementation for MS Fabric.
The procedure I'm doing is as follows:
1. Clear schema export date
2. Reset specific table CompanyInformation-79 (for full reload)
3. Untick the ICParterCode-41 field in the CompanyInformation-79 table
4. Repeat steps 2 & 3 for all BC other companies
5. Delete the CompanyInformation-79 table in Fabric lakehouse and any files in the respective deltas table.

After the above steps, I'm encountering an error message when I attempt to process the "Schema Export" and update the json files in the data lake.  The error message is below:

![image](https://github.com/Bertverbeek4PS/bc2adls/assets/48299239/199645d1-d550-40cc-a376-0403be83f27a)

I couldn't see if this issue was fixed in a prior build or if this is something that will happen after I upgrade the environment to 23.1?  I did see the issue raised (now closed) regarding the error messages from the upgrade.
It seems easy to add new column to a table for export, but not to disable a already exported column?

Thanks in advance for your time on my question.
Greg

**Comment by Bertverbeek4PS** [comment]
I have also created a pull request for this issue.
