### ISSUE TITLE
Multi-company flag after configuration/export

### ISSUE THREAD

**Issue by greglong1** [Bertverbeek4PS/bc2adls#76]
Hi Bert - hopefully a quick question.  In my configuration of adls2bc, I've neglected to switch on the multi-company flag and it appears I cannot change this flag after exporting data.  Is it possible to switch this on?  It doesn't work after clearing the schema export date either.  Perhaps this has been fixed in a later release.  Thanks in advance.

**Comment by greglong1** [comment]
Bert - I've reviewed the config doco and it states that the multi-company flag should only be switched on after the schema (ie all tables and columns) have been finalised.  As the project I'm working on is staged over multiple BC modules, I don't believe I can use the flag as the customer has ongoing BC development which will require changing the schema often.  Can you advise on the benefits of using this flag.  This BC customer as 6 companies, with only one that is fairly large.  Perhaps I should just stagger the Job Queue tasks for each company.  Thanks

**Comment by Bertverbeek4PS** [comment]
Hi @greglong1 then indeed you have got an old version. 
In the newest version (will release today version 2.17) and version before that field is obsoleted.

But in earlier version there was a check that the schema must be exported. Then you can switch the multi company on.
And that schema export is done when you export the data.
So curious what kind of error do you get. Never got that error. I though in earlier code it also check if the schema is the same as in your data lake and BC.

The switch only means that you cannot change the schema inside BC. It will prevent you from doing that. 
That is the only check of the multi-company switch.
You still need to export the data manually or with a job queue for every single company that you want to export.

Hope still will make it clear for you.

**Comment by greglong1** [comment]
Hi @Bertverbeek4PS  - thanks for the update on the field.  I can understand why it's now being obsoleted due to its functionality.  I don't get any error, I simply cannot turn the multi-company radio switch on.  I'll liaise with my BC development team to get the latest update of bc2adls code.  Once again thanks for your time and efforts with this product.  Greg
