### ISSUE TITLE
Object accessibility (Access = Public)

### ISSUE THREAD

**Issue by RandiJakobsen** [Bertverbeek4PS/bc2adls#78]
Hi Bert,
 
I want to hear if it would be possible for you to change the accessibility of the codeunit 82574 "ADLSE External Events" to Public, so that it becomes possible to subscribe to the events in this codeunit?
 
And if the table 82560 "ADLSE Setup" could also become accessible it would be great, but it is not as important to me than getting access to the events in the codeunit.

Best regards,
Randi

**Comment by Bertverbeek4PS** [comment]
Hi @RandiJakobsen for the ADLSE External Events I think it isn't an issue.
But why do you want to get the table ADLSE Setup open? I'm not a fan of that one.

**Comment by RandiJakobsen** [comment]
Hi Bert,

We are running BC 14 on-prem and are due to technical reasons not able to make a connection between BC and Power Automate, so I want to trigger the Fabric Notebook by subscribing to MyBusinessOnExportFinished event. In my subscription I will make the API Request (POST https://api.fabric.microsoft.com/v1/workspaces/4f8a8c2e-86b0-405d-a7e5-a4c84214f1dd/items/bd4ac8cf-67bf-4ae1-a4cb-321844f8d019/jobs/instances?jobType=RunNotebook)

I will need two new fields to hold the "wokspace GUID" and "notebook GUID", and if the ADLSE Setup table were open for extension I would have added the fields here, but I can easily make a new table holding these two fields. 
I fully understand that you will not change the accessibility of the "ADLSE Setup" table, and that is no problem. 

And perfect that you will change the accessibility of the "ADLSE External Events" codeunit.

**Comment by Bertverbeek4PS** [comment]
@RandiJakobsen thanks for the approval. 
It is now merged into the master.
