### ISSUE TITLE
Mix of multiple company tables and common tables

### ISSUE THREAD

**Issue by lhammerbh** [Bertverbeek4PS/bc2adls#81]
Hi Bert
When running the consolidation notebook, I get an error, when it is processing the data from common tables that does not contain the $Company field. Common tables are e.g. AccessControl, Company and User.

I have modified the notebook, so that it checks whether a delta table contains the $Company field. If yes, it does the current processing, if no, it does the same processing, but not using the $Company field.

This updated notebook is attached. The extension is changed from .ipynb to .json in order to upload the file to Github, so you need to rename it back to .ipynb.

[CopyBusinessCentral.json](https://github.com/Bertverbeek4PS/bc2adls/files/14123607/CopyBusinessCentral.json)

**Comment by Bertverbeek4PS** [comment]
Really thanks for the help @lhammerbh!
Indeed that part was missing in the script. Thanks for providing the solution.
I have added it to the main branche.
