### ISSUE TITLE
BC Sales Quotes and Orders to Archive Question

### ISSUE THREAD

**Issue by greglong1** [Bertverbeek4PS/bc2adls#86]
Hi Bert
I'm using bc2adls from BC to Microsoft Fabric and had a quick question regarding the interaction between the Sales and Sales Archive tables.  My understanding is that within BC the Sales Quotes and Orders transaction data (in the Sales Header 36 and Sales Line 37 tables) will move to the Sales Header 5107 and Line 5108 Archive tables once they are converted to invoice or print (dependent upon config).

My understanding from the Fabric notebook is that it will only insert or update (de-duplicate) records.  So when a BC sales transaction moves from the Sales Header/Line to the Sales Header/Line Archive BC tables, the records will stay in the Fabric Sales Header/Line delta tables and also be inserted into the Fabric Sales Header/Line Archive delta tables.  Can you please confirm if this is the case?

Thanks in advance
Greg

**Comment by Bertverbeek4PS** [comment]
Hi @greglong1 indeed if a sales order is archive then it will move from 36/37 to 5107/5108.
So it will delete the records in table 36/37.
Those deletion are also moved to Fabric and the notebook will also delete the records in lakehouse. So they should only appear in the archive tables and removed is from the sales header / sales lines.

**Comment by greglong1** [comment]
Bert - apologies - I see this in the notebook to find deleted records with null values for the SystemCreatedAt_2000000001 field and remove them from the table.  Thanks so much

**Comment by Bertverbeek4PS** [comment]
No problem @greglong1!
