### ISSUE TITLE
Multi-company exports and Power Automate flow

### ISSUE THREAD

**Issue by taylor-moran** [Bertverbeek4PS/bc2adls#87]
Hello,

Very happy to see this project live on here!

For the available Power Automate flow, would there be an issue if multiple companies are being exported simultaneously when it comes to triggering the consolidation pipeline for a table? For example, if the vendor table is being exported for multiple companies at the same, would the consolidation pipeline be triggered multiple times for the vendor table each time a company finishes exporting causing multiple consolidations to happen to the vendor table in Synapse at the same time? The staging process and the deleting deltas by the pipeline if it were to be run simultaneously for a table could cause issues. 

Any insight would be greatly appreciated!

**Comment by Bertverbeek4PS** [comment]
Hi @taylor-moran. If you do a multi company export on Azure Data Lake you must first finish all the export in all companies. If that is done you can run the Synapse pipelines.
Otherwise you can maybe process the file that is in progress of the export from BC.
