### ISSUE TITLE
Unable to remove deleted field from Export ADLS table administration window

### ISSUE THREAD

**Issue by Isarien** [Bertverbeek4PS/bc2adls#93]
Hello

My integrator has removed some obsolete fields in my BC instance. In my case it's in the job table (167). When I try to unselect theses fields from the interface, the windows close unexpectedly, and I get this error : 
![image](https://github.com/Bertverbeek4PS/bc2adls/assets/495394/6b114575-f366-41fd-a6f0-22c8b38bc9f4)
The translation is : 
Field does not exist. Field and identification value : Table No : 167 and N° : 50210

**Comment by Bertverbeek4PS** [comment]
Hi @Isarien,
In the release of 2.18.0 we have added the following button:
![image](https://github.com/Bertverbeek4PS/bc2adls/assets/71499421/d85bb00e-2739-4cda-824c-4e90554c139d)
This will fix the issue that you have.

**Comment by Isarien** [comment]
@Bertverbeek4PS Thank you for your answer. We are on a older version of the plugin, so we do not have this menu. I will ask my integrator to manually delete the lines in the ADLS table configuration, or I will delete and recreate the import in the ADLS interface.

**Comment by Bertverbeek4PS** [comment]
OK then indeed that will be an option. Or migrate to the latest version. In that case you have that option if you need it later on.
