### ISSUE TITLE
Version 2.20 An invalid argument was passed to a 'List' data type method.

### ISSUE THREAD

**Issue by hanksteen** [Bertverbeek4PS/bc2adls#98]
Hi,

Thanks for continuing this product!

I'm having various issues with version 2.20 which I don't get if I instead install version 2.14. Since it is working with 2.14 I don't believe (hope) it is related to my setup in azure or the Setup in the BC page.

I'm not able to export the schema to Azure Data Lake. When I try to export the schema I get the following error.

An invalid argument was passed to a 'List' data type method.

AL call stack: 
"ADLSE Gen 2 Util"(CodeUnit 82568).AcquireLease line 24 - Azure Data Lake Storage Export by The bc2adls team
"ADLSE Communication"(CodeUnit 82562).UpdateCdmJsons line 12 - Azure Data Lake Storage Export by The bc2adls team
"ADLSE Execute"(CodeUnit 82561).ExportSchema line 34 - Azure Data Lake Storage Export by The bc2adls team
"ADLSE Execution"(CodeUnit 82569).SchemaExport line 28 - Azure Data Lake Storage Export by The bc2adls team
"ADLSE Setup"(Page 82560)."SchemaExport - OnAction"(Trigger) line 4 - Azure Data Lake Storage Export by The bc2adls team

I'm not capable of BC debugging on my own :(.

Once I've downgraded to version 2.14 the Schema Export and Export works fine.

**Comment by hanksteen** [comment]
I managed to get some help setting up the debugging.

                ADLSEHttp.InvokeRestApi(Response, StatusCode)
Response = ''
StatusCode = 200
                LeaseIdHeaderValues := ADLSEHttp.GetResponseHeaderValue('x-ms-lease-id');
Return an empty list
                LeaseIdHeaderValues.Get(1, LeaseID);
Fails because there is no item 1 in the list.

**Comment by Bertverbeek4PS** [comment]
Hi @hanksteen expect some delay because currently this week and next week I'm at a business event.

Sorry that there is an error in it! I will have a look when I got time.

**Comment by acjdekorte** [comment]
I am running into the same issue on an environment, while it runs perfectly on the other. The failed environment is a cloud environment on a different tenant compared to the tenant of Azure Data Lake. The environment in which it is successfull is a OnPrem environment. May be this information is beneficial when trying to solve the issue.

**Comment by hanksteen** [comment]
I'm on cloud as well, but Azure and BC is in the same tenant.

**Comment by acjdekorte** [comment]
I think that I found the real issue (which should be fixed in version 2.21).

The code of InvokeRestApi (codeunit 82563 "ADLSE Http") does an exit, when the call is successfull on line 143
![image](https://github.com/Bertverbeek4PS/bc2adls/assets/36184654/842b3880-505d-4a70-983f-0dd584fecf10)

But the response is retrieved on line 192-193, which is never reached by the code.
![image](https://github.com/Bertverbeek4PS/bc2adls/assets/36184654/4bcfccea-58d4-4255-9466-314ef9c076bf)

Unfortunately I am not able to test at our environment, since I am lacking the sufficient rights to install extensions.

**Comment by Bertverbeek4PS** [comment]
@acjdekorte @hanksteen I have tested the newest package that you can find here:
https://github.com/Bertverbeek4PS/bc2adls/releases/tag/2.20.0
And it is working correctly on that version.

Sorry for the bug in it!

**Comment by hanksteen** [comment]
I tried with The bc2adls team_Azure Data Lake Storage Export_2.21.63.0.app and now it worked.
Thanks for the fix!
